### ISSUE TITLE
[FSE] iframeエディターインスタンスでの動作確認

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe-blocks-pro#11]
ブロックテーマを適用し、サイトエディター（iframe）で各ブロックが動作し壊れないかチェックする。

**Comment by ddryo** [comment]
編集メモ: プレビューに関しては別issueでまとめていくため、FSEでのサイトエディター上での問題のみここに書いていく感じにします。

**Comment by ddryo** [comment]
ただ、FSEで使われるケースに関しての対応はとりあえず後回しでいきます。
