### ISSUE TITLE
リストブロック：番号付きリストの番号が正しく採番されない

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe-blocks-pro#14]
- スタイルが「番号付き」の時は、「リストの数字を逆順にする」をオンにするとマイナス表示になる。
- スタイルが「注釈」の時は、「リストの数字を逆順にする」をオンにしても反応しない。

https://user-images.githubusercontent.com/54422211/150500120-1055a3e3-24e8-4a04-b114-d798a9a19fbe.mp4

**Comment by ddryo** [comment]
> スタイルが「番号付き」の時は、「リストの数字を逆順にする」をオンにするとマイナス表示になる。

あれ、これが正しい挙動かと思ってましたが、なにか勘違いしてましたっぽいです...。

> スタイルが「注釈」の時は...

これは確実にミスってますね...。


ちょっと時間かかりそうなので、5.9対応のあとでやります！
