### ISSUE TITLE
ボックスリンクブロック：スタイルプレビューに背景画像が表示されない

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe-blocks-pro#17]
![box_2](https://user-images.githubusercontent.com/54422211/150513627-03061086-0ccc-4826-9f61-4e567acfec28.png)

**Comment by t-hamano** [comment]
画像は適用されているようだが、`.arkb-boxLink__inner` に `height: 100%` が適用されていると、ボックスの高さが0 になる様子。

https://user-images.githubusercontent.com/54422211/150629341-c684965a-1a92-4324-b8b8-e66fbf1be9fd.mp4

おそらく、フレックスボックスの子・孫要素でないと `height: 100%` が効かないと予想するが、このスタイルを消す事は出来ないので、親要素の `arkb-boxLink ` を `display:flex` にする事で対処します。
※`arkb-boxLink ` の子は `.arkb-boxLink__inner` だけなので、フレックスレイアウトにする事の影響は無い。

**Comment by ddryo** [comment]
flexにしてしまうと画像比率の設定がある時にバグるので、revertします。

<img width="903" alt="スクリーンショット 2022-01-24 16 01 11 1" src="https://user-images.githubusercontent.com/31400297/150737571-558f5388-a4db-4353-9953-7903a5190c9c.png">

**Comment by ddryo** [comment]
今回の問題は、プレビューエリアではflexな親ブロック（.arkb-columns）がなく子ブロック単体でプレビューに存在することになり、その状態で height100% になっていることでした。

なので .arkb-columns 内のときにheightを当てるように修正する形で対応しました。（今後ボックスリンクを単体で使えるようにする可能性もなくはないので、今のうちにこの現象が見つかってよかったです！ありがとうございます。）
